version: "3.3"

volumes:
  database:
    driver: "local"

services:
  pg-admin:
    image: dpage/pgadmin4
    ports:
      - 6666:80
    environment:
      PGADMIN_DEFAULT_EMAIL: adm@adm.ru
      PGADMIN_DEFAULT_PASSWORD: admin123
  database:
    container_name: testing-api
    image: postgres:11-alpine
    ports:
      - 15432:5432

    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: admin123
      POSTGRES_DB: testing
      PGDATA: /var/lib/postgresql/data/pgdata
