version: "3.3"
networks:
  lesson:
    driver: bridge
volumes:
  database:
    driver: "local"

services:
  lesson-database:
#    container_name: lesson-db
    image: postgres:11-alpine
    networks:
      - lesson
    ports:
      - 15432:5432
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: admin123
      POSTGRES_DB: testing
      PGDATA: /var/lib/postgresql/data/pgdata
  api:
    depends_on:
      - lesson-database
    container_name: lesson-api
    build:
      context: ./api
    volumes:
      - ../:/var/www/
    networks:
      - lesson
    ports:
    - 5555:5555
